"""add title to product tracker

Revision ID: 48471a851d9c
Revises: c3728864c176
Create Date: 2026-04-26 13:18:59.178308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48471a851d9c'
down_revision: Union[str, None] = 'c3728864c176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_trackers', sa.Column('title', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_trackers', 'title')
    # ### end Alembic commands ###
